version: '3.8'

services:
  xxe-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "29676:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./src:/app/src:ro
      - ./flag.txt:/flag.txt:ro
      - maven-repo:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  maven-repo: