"""change winner to id

Revision ID: 7d2611ade73e
Revises: bd3acaf945a4
Create Date: 2024-11-28 11:36:20.256346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2611ade73e'
down_revision: Union[str, None] = 'bd3acaf945a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'elections', 'candidates', ['winner_id'], ['id'])
    op.drop_column('elections', 'winner_name')
    op.drop_column('elections', 'winner_votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('winner_votes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('elections', sa.Column('winner_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.drop_column('elections', 'winner_id')
    # ### end Alembic commands ###
